### ISSUE TITLE
Chyby pre delenie desatinnych cisiel

### ISSUE THREAD

**Issue by xzauko** [xzauko/pb173-project#11]
Delenie `decimal("0.125")/decimal("0.005")` - vysledok `10::p.000` - nedodrzanie radixu (ciselne toto spravne)
Cisla:

```
decimal a("12.145");
const decimal c("12");
```

Ocakavane vysledky:
`a/c == decimal("1.012");`
Skutocny vysledok:
`a/c == decimal("1.000");`

**Comment by xpocho** [comment]
a/c == decimal("1.000"); je správný výsledek, alespoň podle bc:
12.145 / 12
1

**Comment by xpocho** [comment]
problém decimal("0.125")/decimal("0.005") by měl být vyřešen v posledním komitu v xpocho_features

**Comment by xzauko** [comment]
bc:

```
scale = 3 # set to max(scale, other.scale) manually
12.145/12
1.012
```

**Comment by xpocho** [comment]
Kompletně jsem předělal dělení, a opravil jsem testy tak, aby to odpovídalo chování bc

**Comment by xzauko** [comment]
Otestujem, ak vsetko v poriadku tak pridam do svojho branchu v pull requeste. Mozno este urobim tu drobnu upravu, ze namiesto max z 2 scale vzdy zoberieme ten z prveho pre delenie - co si o tom myslis?

**Comment by xpocho** [comment]
uprřímně uvažuju jestli by nebylo lepší udělat scale jako statický atribut?

**Comment by xzauko** [comment]
Potom ako verejny asi, vsak?

**Comment by xpocho** [comment]
jo, jinak by se nedal nijak rozumě nastavit

**Comment by xzauko** [comment]
Okej pozriem sa co vsetko by trebalo pomenit u mna.

**Comment by xpocho** [comment]
Problém by mohl být s  modulem, protože pro nenulové scale vrací číslo s větší desetinou částí než je scale. Buď by se muselo useknout, nebo zvětšit scale.

**Comment by xzauko** [comment]
To nie je problem, vracia zvysok po deleni na scale desatinnych miest.
